Django qset
alphabestteam/Matan pull request #27
Opened 2023-10-17 07:58 UTC by matangino7

2023-10-18 13:30 UTC, alphabestteam requested changes
יש לתקן ע"פ ההערות

2023-10-18 13:30 UTC, alphabestteam commented on persons/person/views.py
> +            print(parent)
שים לב, בתרגיל הובהר שיש לקבל את הנדרש כתוצאה לשאילתא אחת, יש לתקן

2023-10-18 13:30 UTC, alphabestteam commented on persons/person/views.py
> +        kids = query_set.kids.all().values('name', 'date_of_birth', 'city')
זה לא בהכרח יתן אותם מסודרים בסדר מהגדול לקטן, קיים שינוי בסעיף הספציפי, הסתכל עליו שוב

2023-10-18 13:30 UTC, alphabestteam commented on persons/person/views.py
> +        count = query_set.count()
לא היה צורך לפצל ל 2 שורות (הכוונה הייתה שאילתא אחת בלבד)

2023-10-18 13:30 UTC, alphabestteam commented on persons/person/views.py
> +        richest_parent = richest_parents.first()
יש לעשות זאת בשאילתא אחת ושורה אחת בלבד

2023-10-18 13:30 UTC, alphabestteam commented on persons/person/views.py
> +        kids = kids.filter(total_parent_salary__gt=50000)
יש לעשות זאת בשאילתא אחת בעלת שורה אחת, יש פה פילטורים מיותרים

2023-10-19 06:18 UTC, matangino7 commented on persons/person/views.py
> +            print(parent)
השאילתא עצמה היא אכן בשורה אחת , השאר זה נטו ההדפסה

2023-10-19 06:30 UTC, closed without merging